# This is more compatible
version: '2.0'
# We probably want this in future
#version: '3.1'

services:
  # This is the MongoDB database server
  mongo:
    image: mongo:4.0.10 # Latest stable (released: 2019-05-31)
    restart: always
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    volumes:
      - mongodb:/data/db


  # This is the optional Web interface to MongoDB
  mongo-express:
    image: mongo-express:0.49
    depends_on:
      - mongo
    restart: always
    ports:
      # Bound locally, so you will need to ssh-port forward in order to access the interface
      - 127.0.0.1:${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo


volumes:
  mongodb: {}
